### ISSUE TITLE
ImportError: this version of pandas is incompatible with numpy < 1.12.0

### ISSUE THREAD

**Issue by CeciliaDeng** [RVanDamme/MUFFIN#16]
Hi @RVanDamme, I'm keen to try MUFFIN and ran the test with command

`git clone https://github.com/RVanDamme/MUFFIN.git`
`nextflow run RVanDamme/MUFFIN --output /workspace/18_MUFFIN/01_TEST --rna --cpus 8 --memory 32g -profile local,singularity,test`

A README_output.txt and subset/ directory were created under the output folder. However, the process failed with 

> Command executed:
  mkdir concoct_out
  cut_up_fasta.py assembly.fasta -c 10000 -o 0 --merge_last -b contigs_10K.bed > contigs_10K.fa
  samtools index -@ 8 ont_sorted.bam
  samtools index -@ 8 illumina_sorted.bam
  concoct_coverage_table.py contigs_10K.bed *.bam > coverage_table.tsv
  concoct --composition_file contigs_10K.fa --coverage_file coverage_table.tsv -b concoct_out --thread 8
  merge_cutup_clustering.py concoct_out/clustering_gt1000.csv > concoct_out/clustering_merged.csv
  mkdir fasta_bins
  extract_fasta_bins.py assembly.fasta concoct_out/clustering_merged.csv --output_path fasta_bins
> Command exit status:
  1
Command output:
  (empty)

> Command error:
  Traceback (most recent call last):
    File "/opt/conda/bin/concoct_coverage_table.py", line 18, in <module>
      import pandas as pd
    File "/opt/conda/lib/python2.7/site-packages/pandas/__init__.py", line 23, in <module>
      from pandas.compat.numpy import *
    File "/opt/conda/lib/python2.7/site-packages/pandas/compat/numpy/__init__.py", line 24, in <module>
      'this pandas version'.format(_np_version))
  ImportError: this version of pandas is incompatible with numpy < 1.12.0
  your numpy version is 1.8.1.
  Please upgrade numpy to >= 1.12.0 to use this pandas version
 Work dir:
  /workspace/Other/work/d7/9a3c7a714f6185250a30a77d58d70d
  Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh

How to fix this, please? Thought numpy/panda versions were packed in the singularity image. 
Where is the _.command.sh_ file? I can't find it under the current dir, the output dir, or the Work dir.
Thanks.

**Comment by replikation** [comment]
hi
* iam currently running singularity test runs to reproduce the error
* yes the deps are located in an image build from a (working) dockerimage, iam also confused about this error, ill come back at you

**Comment by replikation** [comment]
Hi,

i was not able to reproduce the error. would you please manually remove the concoct image and retry it? I tested the most recent master from git and let it rebuild (singularity images) and download everything ("clean slate").

these are the images created and used during the test run (located in ./work/singularity), please check also the sizes. singularity images sometimes have issues

````bash
533M Nov 17 18:22 nanozoo-checkm-1.1.3--c79a047.img
458M Nov 17 10:39 nanozoo-concoct-1.1.0--03a3888.img
213M Nov 17 10:17 nanozoo-eggnog-mapper-2.0.1--d5e0c8c.img
203M Nov 17 10:21 nanozoo-fastp-0.20.0--78a7c63.img
515M Nov 17 10:36 nanozoo-maxbin2-2.2.7--b643a6b.img
228M Nov 17 10:38 nanozoo-metabat2-2.13--0e2577e.img
1.3G Nov 17 17:45 nanozoo-metawrap-v1.3--a7eb9af.img
208M Nov 17 10:36 nanozoo-minimap2-2.17--caba7af.img
386M Nov 17 10:36 nanozoo-pilon-1.23--b21026d.img
368M Nov 17 18:21 nanozoo-sourmash-2.0.1--6970ddc.img
200M Nov 17 10:29 nanozoo-spades-3.13.1--2c2a4c0.img
222M Nov 17 10:17 nanozoo-template-3.8--ccd0653.img
````

**Comment by CeciliaDeng** [comment]
Thank you, @replikation. The test run has been pulling images and I haven't got the numpy error yet. Will try on real data if the test run finishes ok.
