### ISSUE TITLE
Report "unused reads" back to the user

### ISSUE THREAD

**Issue by replikation** [RVanDamme/MUFFIN#17]
* report back the number of unused reads back to the User.
* Should/Could look like this

````
nanopore reads:  500,000 reads used from 2,000,000
Illumina reads:  2500,000 reads used from 3,000,000
````

can be provided as a file in the "unused reads dir" or as a final terminal print

**Comment by microbemarsh** [comment]
I think it would also be useful to report the .gfa files from the assemblers to view the MAGs with [Bandage](https://github.com/rrwick/Bandage)
