### ISSUE TITLE
Running binning only with pre-made assembly

### ISSUE THREAD

**Issue by ghost** [RVanDamme/MUFFIN#19]
Hi all,

I would like to run your binning/bin refinement module with an assembly that I already have. Is there a way to do so?

Thanks!

**Comment by RVanDamme** [comment]
Hi!

Currently, this is not possible to do in the pipeline.
If you only care about the binning and bin refinement I strongly suggest you look at the MetaWRAP pipeline where they do that (we integrate their refinement step in our pipeline).
