### ISSUE TITLE
ToDo tracklist

### ISSUE THREAD

**Issue by replikation** [RVanDamme/MUFFIN#2]
# todo - tracklist:
* dummy data to osf for readme
* what workloadmanager to add for now pre-configured?
* What can we test?
  * SLURM
  * LSF ( ill have some code for this)

**Comment by RVanDamme** [comment]
* Dummy data available here https://osf.io/m5czv/ or can be tested with and automatic download as explain in the README.md
* For now local, Gcloud and SLURM are available
* LSF will be implemented in the next update once tested
