### ISSUE TITLE
Due to Spades bug #863, conda.config does not work for MUFFIN

### ISSUE THREAD

**Issue by marade** [RVanDamme/MUFFIN#26]
https://github.com/ablab/spades/issues/863

Until Spades 3.15.4 is released, it works properly with these changes:

withLabel : spades { conda = 'bioconda::spades=3.15.3'}
withLabel : python38 { conda = 'python=3.9 '}

**Comment by RVanDamme** [comment]
Hello,

Thanks for reporting this I will fix this and update as soon as Spades 3,15,4 is released
