### ISSUE TITLE
CPU ERROR

### ISSUE THREAD

**Issue by H1889** [RVanDamme/MUFFIN#28]
Hi, I have installed MUFFIN locally, when run the test:
 NXF_VER=20.10.0 nextflow run ./MUFFIN --output output_dir  --cpus 8 --memory 16g -profile local,conda,test

everything goes well, however when I run 

NXF_VER=20.10.0 nextflow run ./MUFFIN --output output_dir  --cpus 32 --memory 128g -profile local,conda,test

an error is shown:
Error executing process > 'readme_output'

Caused by:
  Process requirement exceed available CPUs -- req: 32; avail: 12

Command executed:

  wget --no-check-certificate https://osf.io/a6hru/download -O README_output.txt

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /home/ggpozo/Pelomyxa_schiedti/GENOMA_AUTORES/work/b5/87764226137633313bb95a3128b680

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

But in my system I have 64 cores:
 nproc --all
64

Any suggestions?

Thanks for the help.

best

**Comment by replikation** [comment]
hi,

could you update nextflow. otherwise, the error is strange and is part of nextflow and not muffin so not 100 % sure what is going on.

**Comment by H1889** [comment]
Thanks, but if I update nextflow Muffin does not work, for that reason I run with NXF_VER=20.10.0, last version 21 is incompatible with MUFFIN. When I use it MUFFIN does not work at all:

./nextflow run ./MUFFIN --output MUFFIN_PRUEBA  --cpus 32 --memory 128g -profile local,conda,test
N E X T F L O W  ~  version 21.10.6
Launching `./MUFFIN/main.nf` [intergalactic_hamilton] - revision: d488d29b21

and ends doing nothing as other issues have discussed here.

**Comment by replikation** [comment]
identified the bug with the versions. (pushed it to the main branch) currently running some test. but nextflow >21 starts now

**Comment by H1889** [comment]
I am using:
Ubuntu 20.04.3 LTS
In a docker image system with 64 cores and 256Mb RAM

**Comment by H1889** [comment]
However I have tested the same in my own local machine with 32 cpu and is working without error under Ubuntu 20, it seems that the problem is caused by my remote virtual machine under docker. I can use in this "virtual machine" the 64 cores with other programs without any problem. It sounds nextflow does not like to be executed under "virtualization".

**Comment by replikation** [comment]
ah so its a virtual machine than this error happens because your VM does not have access to all the cores

**Comment by replikation** [comment]
e.g. you get the same error in the cloud if you start a node with e.g. 10 cores and request 12 for a process

**Comment by H1889** [comment]
I am not the administrator of the system, but I can use all the cores when running other software. Anyway I can run Muffin on my local machine with 32 cores and forget running it on my remote system.
Best wished and thanks for the help.
