### ISSUE TITLE
MAXBIN2 RUNNING ONLY IN ONE CORE?

### ISSUE THREAD

**Issue by H1889** [RVanDamme/MUFFIN#29]
Hi, again, I am running the test, in may local machine with these options:
NXF_VER=20.10.0 nextflow run ./MUFFIN --output output_dir --cpus 32 --memory 128g -profile local,conda,test

Everything goes well and very fast, however when it starts bowie2 mapping the process only uses one cpu and lasts for hours (at this moment 5 hours):

N E X T F L O W  ~  version 20.10.0
Launching `./MUFFIN/main.nf` [jovial_khorana] - revision: d488d29b21
executor >  local (12)
[71/468286] process > test                   [100%] 1 of 1 ✔
[skipped  ] process > sourmash_download_db   [100%] 1 of 1, stored: 1 ✔
[skipped  ] process > checkm_download_db     [100%] 1 of 1, stored: 1 ✔
[e2/5d8557] process > checkm_setup_db        [100%] 1 of 1 ✔
[3f/fe885e] process > discard_short (1)      [100%] 1 of 1 ✔
[24/be841a] process > merge (1)              [100%] 1 of 1 ✔
[a1/96b732] process > fastp                  [100%] 1 of 1 ✔
[7e/73a2a0] process > spades (1)             [100%] 1 of 1 ✔
[17/ea6bbe] process > minimap2 (1)           [100%] 1 of 1 ✔
[e1/80871e] process > bwa (1)                [100%] 1 of 1 ✔
[31/99bc17] process > metabat2 (1)           [100%] 1 of 1 ✔
[79/521710] process > maxbin2 (1)            [  0%] 0 of 1
[5f/6dcc0b] process > concoct (1)            [100%] 1 of 1 ✔
[-        ] process > refine3                -
[-        ] process > checkm                 -
[-        ] process > sourmash_bins          -
[-        ] process > sourmash_checkm_parser -
[skipped  ] process > eggnog_download_db     [100%] 1 of 1, stored: 1 ✔
[-        ] process > eggnog_bin             -
[-        ] process > parser_bin             -
[71/ae962c] process > readme_output          [100%] 1 of 1 ✔

is the maxbin2 phase where the process is stuck? I have checked it with htop and see only one cpu used at 100% by the bowtie2 process.

Thanks

**Comment by replikation** [comment]
thanks for reporting this there was a missing "2" in the config. therefore maxbin2 did not received the info on a local run to use all cores.

**Comment by H1889** [comment]
Ok, you are wellcome. Thanks to you for doing a nice pipeline.
best
