### ISSUE TITLE
Error while running pipeline

### ISSUE THREAD

**Issue by aditi48n** [RVanDamme/MUFFIN#38]
Hello, 

I am new to nextflow and have trouble understanding this error. Any help would be highly appreciated. 

Error:
Error executing process > 'maxbin2 (1)'

Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /home/aditi48n/work/conda/env-9688beee8668b9c389c89a26d3c36f2c bioconda::maxbin2=2.2.7
  status : 143
  message:

The command I used is as follows: `./nextflow run RVanDamme/MUFFIN -params-file /home/aditi48n/tools/MUFFIN/MUFFIN_params.yml -profile local,conda,test
`

Params file contents is:
assembler   : "metaflye"
ouptut      : "/home/aditi48n/data/hybrid_assembly/muffin/long_read_assembler"
illumina    : "/home/aditi48n/data/hybrid_assembly/short_reads/"
ont         : "/home/aditi48n/data/hybrid_assembly/long_reads/"
cpus        : 4
memory      : "16g"
modular     : "full"
rna         : false
bin_classify: false
bin_annotate: false

**Comment by replikation** [comment]
hi, sorry for the late reply. seems to be related to conda are you able to create a conda environment on your computer for maxbin2?  (this one `bioconda::maxbin2=2.2.7`)

**Comment by replikation** [comment]
conda is rather bad at installing stuff. might be worth a try to install singularity or docker and use this or install singularity via conda and run singularity via the profile.

**Comment by aditi48n** [comment]
Hello, sorry for the late response and thank you for your help. I tried to create a new environment for maxbin2 but it failed. Docker also failed with the following error. I am yet to try singularity. 

Error trying to run docker: 

Error executing process > 'readme_output'

Caused by:
  Process `readme_output` terminated with an error exit status (126)

Command executed:

  wget --no-check-certificate https://osf.io/a6hru/download -O README_output.tx

Command exit status:
  126

Command output:
  (empty)

Command error:
  docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=nxf-sbPGQn2LYaSr42p3We0ZlbmQ": dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /home/aditi48n/work/e5/435b3e02b6b88e1d448a6f792727fd

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by replikation** [comment]
````
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=nxf-sbPGQn2LYaSr42p3We0ZlbmQ": dial unix /var/run/docker.sock: connect: permission denied.
````

do you have sudo rights on your docker to run it? seems like it has no rights. 

if you are admin on your own system do `sudo usermod -a -G docker $USER`  to give docker some rights for yourself

**Comment by aditi48n** [comment]
I am running this on a server and dont have sudo permissions. I also tried singularity and got errors: 

Error executing process > 'eggnog_download_db'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name nanozoo-eggnog-mapper-2.0.1--d5e0c8c.img.pulling.1657568631122 docker://nanozoo/eggnog-mapper:2.0.1--d5e0c8c > /dev/null
  status : 127
  message:
    WARNING: pull for Docker Hub is not guaranteed to produce the
    WARNING: same image on repeated pull. Use Singularity Registry
    WARNING: (shub://) to pull exactly equivalent images.
    /usr/bin/env: ‘python’: No such file or directory
    ERROR: pulling container failed!

The command I used was: 
./nextflow run RVanDamme/MUFFIN --output results_dir --rna -profile local,singularity,test

**Comment by aditi48n** [comment]
I also used the local install for singularity instead of conda install to run the pipeline and got the following error:

Error executing process > 'readme_output'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name nanozoo-template-3.8--ccd0653.img.pulling.1657571249274 docker://nanozoo/template:3.8--ccd0653 > /dev/null
  status : 255
  message:
    INFO:    Converting OCI blobs to SIF format
    INFO:    Starting build...
    Getting image source signatures
    Copying blob sha256:3a8378bed433f4317b548cc3c30600c53b21597bceefa660b37775ad4fb72166
    Copying blob sha256:b8f262c62ec67f02536f49654de586c022043652bbb6bbf76a8dab1542627a8d
    Copying blob sha256:906d7b5da8fb08f9d6c98d3e7df1d621d03d249c26524b64b09641b1f70fc27e
    Copying blob sha256:0a43c0154f168ca6fe36f31e366dc85ba2f95da95a9bf69399d927d513d501f9
    Copying blob sha256:b1e93c6d599519e2acaeb784e4210fd7f63ed0f50c96b89a9b71669676bb3ac5
    Copying blob sha256:27cfc19a0b7304dbc9799729095ce7c348535b164d426eb8935dd576527b9ac0
    Copying config sha256:de384d760cd2fd0a4295e1aed7d58a3d42ca81a871dad8483c26a8302e583a57
    Writing manifest to image destination
    Storing signatures
    FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: conveyor failed to get: no descriptor found for reference "sha256.6df195855b48d7e923cdcf440e4c4f58ea37bf3855fb01d68dab928aba7fe4f6"

The command I used: `./nextflow run RVanDamme/MUFFIN -params-file /home/aditi48n/tools/MUFFIN/MUFFIN_params.yml -profile local,singularity `
