### ISSUE TITLE
`eggnog_download_db'` failed because `download_eggnog_data.py` not found

### ISSUE THREAD

**Issue by RemiMaglione** [RVanDamme/MUFFIN#8]
Hello, 
`eggnog_download_db'` failed because `download_eggnog_data.py` not found. 
I don't know if it's an issue from my side but I download and install it on the metwarp-env with:
`conda install -c bioconda eggnog-mapper`
Since I'm kind of new in the conda env dynamics,even if the eggnog install went well, the download_eggnog_data.py are now on my env path, but the main.nf keep failing at that step. I had to manually download the eggnog db by running: 
`nextflow run /path/to/my/MAFIN/modules/eggnog_get_databases.nf`
[Which worked, proving that download_eggnog_data.py are accessible for this module but now for the main.nf (???)]
Thanks for your help

_Originally posted by @RemiMaglione in https://github.com/RVanDamme/MUFFIN/issues/7#issuecomment-613577091_

**Comment by RVanDamme** [comment]
Hello,
The release 1.0.0 of MUFFIN should have the issue fixed.
If a new issue or this one persists, please come back to us
