### ISSUE TITLE
`checkm_setup_db` steps appears unusually long

### ISSUE THREAD

**Issue by RemiMaglione** [RVanDamme/MUFFIN#9]
Hello,
`checkm_setup_db` steps appears unusually long (I checked the code of both `checkmgetdatabases.nf `and `checkmsetupDB.nf` and it looks like a download and installation of the checkm database: it should not took more than 2 hours, or should it ?)
So I kill the main command and manually launch the checkmgetdatabases with `nextflow run checkmgetdatabases.nf` and now the pipeline moved to the fastp step. 
Thanks for your help

_Originally posted by @RemiMaglione in https://github.com/RVanDamme/MUFFIN/issues/7#issuecomment-613645526_

**Comment by RVanDamme** [comment]
Hello,
The release 1.0.0 of MUFFIN should have fixed the issue.
If it's not fixed yet please come back to us.
